version: '3.7'
services:
  slim:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: slim

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./apiapp:/var/www/html
    privileged: true
    ports: 
      - '8080:80'
    links: 
      - 'slim'